version: "3.8"
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME = tamim
    #   - MONGO_INITDB_ROOT_PASSWORD = 12345
    env_file:
      - ./env/mongo.env
  # backened:
  #  frontend:

volumes:
  data: