services:
  server:
    image: "nginx:stable-alpine"
    ports: -'8000:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.com:ro

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated 

  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
  
  composer:

  # artisan:

  # npm:
